### ISSUE TITLE
Adding DPT  sub-types?

### ISSUE THREAD

**Issue by greiginsydney** [mhthies/knxdclient#4]
Hi Michael,

I stumbled across knxdclient yesterday and I'm loving it! Thank you for that.

I was wondering if you've considered extending it to decode the [DPT types](https://support.knx.org/hc/en-us/articles/15392604906514-Interworking-Datapoint-types)?

Or is it your intent that the consumer of the client will provide the required formatting of the raw value returned by the client?

\- Greig.

**Comment by mhthies** [comment]
Hi Greig,

the functionality for encoding/decoding most of the KNX datapoint types is already present in the library, see `knxdclient.encode_value()` and `knxdclient.decode_value()` from the `knxdclient.encoding` module. Since the client cannot know the DPT of a specific group address, the consumer code needs to invoke `encode_value()`/`decode_value()` explicitly with the correct DPT, as demonstrated in the examples in the Readme file.

Adding DPT sub-types to the encoding/decoding functions does not seem sensible to me, because the sub-types only specify the semantics of the value, not the value data type or its encoding/decoding. So it's totally up to the conusmer code to interpret the decoded value according to a the DPT sub-type – if it is known.

**Comment by greiginsydney** [comment]
Hi Michael,

Thanks. I thought it worthwhile enquiring before I take on the burden of adding it locally.  ;-)

(I have the sub-types already because they came from the same GA export where the DPTs that decode_value()) needs came from.)

If I manage to code anything credible I'll ping you and see if you like the look of it for a PR.

\- G.
